### ISSUE TITLE
No support for audio posts

### ISSUE THREAD

**Issue by Lovasz-Akos** [sneat/patreon-downloader#10]
Using it on a podcast's patreon only downloads images, none of the audios

**Comment by Lovasz-Akos** [comment]
Didn't check the source code yet, but if you're filterig by classes, they always have a source link in an <audio> tag, opening the link results in automatically downloading the file.
![image](https://user-images.githubusercontent.com/55391231/185742324-ae91b608-0030-489f-a147-21d6d1820c65.png)

**Comment by Lovasz-Akos** [comment]
[this](https://github.com/deathbydeprecation/patreon-audio-downloader) firefox only extension is specialised in audio downloads, maybe it can help?

**Comment by sneat** [comment]
I might need to see an example post, or at least the data attached to the post. They must be attaching the audio in a different way to what I expect (perhaps embedding in the content rather than attaching to the post).

This public post for instance works (since it's the method I expect) - https://www.patreon.com/posts/new-ambience-35325847

Would you be able to chat to me on Discord (https://discord.gg/NQkFhnxcqC) at some stage?

**Comment by Lovasz-Akos** [comment]
they indeed use a (probably patreon's own) embedded audio player thingy that looks like this, it's not just attached to the post.
![image](https://user-images.githubusercontent.com/55391231/187203070-b42d5ceb-7f05-4362-8fcd-570544bb6c6b.png)
here's some podcast using the same feature that's a public post so you can disect it yourself :D 
https://www.patreon.com/posts/646-liv-strong-7-69272897

**Comment by sneat** [comment]
@Lovasz-Akos interestingly, that post works correctly for me. I see 3 files listed, and end up with a 101MB mp3 file which plays correctly.

What are you seeing?

![image](https://user-images.githubusercontent.com/293277/187341539-70cddbb7-cebb-4425-9c9f-5fb6cc841db5.png)
