### ISSUE TITLE
An issue when use patron downloader

### ISSUE THREAD

**Issue by SaberMarionetteJ** [sneat/patreon-downloader#2]
Sorry to ask you that, is there any tutorials for the patron downloader? I have installed the downloader. But the button on the chrome tool box is grey. I can't download pictures by press it when on the patron website. How to use that?

**Comment by sneat** [comment]
@SaberMarionetteJ can you press the F12 key and see if there are any errors listed in the Console?

It only works while on an individual Patreon post, not on the overview page for a creator.

Are you able to share the link to the post you are trying to download?

**Comment by sneat** [comment]
@Snap-i thanks for the additional information. That error is unrelated to patreon downloader, it's to do with sendbird - perhaps another extension you have installed?

As for the button being blue, it only support some formats of videos. Is the post you are trying to download from a public post at all so that I can test against it?

**Comment by sneat** [comment]
VLC (a popular video player) has a Convert/Save option that will take the playlist and allow you to save it to mp4. That's what I would do.

**Comment by sneat** [comment]
[Release v1.1.1](https://github.com/sneat/patreon-downloader/releases/tag/1.1.1) adds a notice about better ways to download the videos from Patreon.
